// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BiblioSol.Domain.Entities;

[Table("TipoNotificacion", Schema = "Notificaciones")]
public class Notificacion
{
    [Key]
    public int IdNotificacion { get; set; }

    public int PrestamoId { get; set; }

    public int? PlantillaId { get; set; }


    public int TipoNotificationId { get; set; }

    public string Mensaje { get; set; }


    public DateTime FechaEnvio { get; set; }

    public DateTime FechaCreacion { get; set; }


    public int UsuarioCreacionId { get; set; }


    public DateTime? FechaMod { get; set; }


    public int? UsuarioMod { get; set; }


    public bool Active { get; set; }

}