// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BiblioSol.Domain.Models;

/// <summary>
/// Registrar todos los roles de los usuarios.
/// </summary>
[Table("Roles", Schema = "Seguridad")]
public class Rol
{
    /// <summary>
    /// Identidicador unico del rol.
    /// </summary>
    [Key]
    public byte RolId { get; set; }

    /// <summary>
    /// Nombre del rol.
    /// </summary>
    public string Nombre { get; set; }

    /// <summary>
    /// Guardar la fecha en que se creo el registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Guardar el id del Usuario que creo el registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Fecha en que se modifico el registro
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Usuario que modifico el registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Informa si el registro fue o no eliminado.
    /// </summary>
    public bool Active { get; set; }

    public virtual ICollection<UsuariosRole> UsuariosRoles { get; set; } = new List<UsuariosRole>();
}