// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace BiblioSol.Domain.Entities;

/// <summary>
/// Tipos de notificaciones que se utilizaran.
/// </summary>
[Table("TipoNotificacion", Schema = "Notificaciones")]
public class TipoNotificacion
{
    /// <summary>
    /// Identidicador unico del tipo de notificaion.
    /// </summary>
    [Key]
    public int IdTipoNotificacion { get; set; }

    /// <summary>
    /// Descripcion del tipo de notificaion.
    /// </summary>
    public string Descripcion { get; set; }

    /// <summary>
    /// Guardar la fecha en que se creo el registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Guardar el id del Usuario que creo el registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Fecha en que se modifico el registro
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Usuario que modifico el registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Informa si el registro fue o no eliminado.
    /// </summary>
    public bool Active { get; set; }

}