// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BiblioSol.Domain.Models;

/// <summary>
/// Guarda la relacion del rol con el usuario.
/// </summary>
[Table("UsuariosRoles", Schema = "Seguridad")]
public class UsuariosRol
{
    /// <summary>
    /// Identidicador unico del Usuario.
    /// </summary>
    [Key]
    public int UsuarioId { get; set; }

    /// <summary>
    /// Identidicador unico del rol.
    /// </summary>
    public byte RolId { get; set; }

    /// <summary>
    /// Guardar la fecha en que se creo el registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Guardar el id del Usuario que creo el registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Fecha en que se modifico el registro
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Usuario que modifico el registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Informa si el registro fue o no eliminado.
    /// </summary>
    public bool Active { get; set; }

    public virtual Rol Rol { get; set; }
}